name: Concurrency Group No. 2
on:
  push:
    branches: feature/concurrency
jobs:
  do-things:
    name: Do Other Things With Concurrency
    runs-on: ubuntu-latest
    concurrency: 
      group: static-group
      cancel-in-progress: true
    steps:
      - name: The Other Thing I've Done
        run: echo "I've done another thing!"; sleep 15;
